### ISSUE TITLE
Thanks! And a note!

### ISSUE THREAD

**Issue by ewdurbin** [makecodes/django-dbml#9]
You can close this, but I wanted to provide some additional context on the PRs submitted (#7 and #8).

The Python Software Foundation is currently doing Privacy and Data policy work, which necessitates creation of data maps for our various services. We run a _lot_ of Django.

Our end goal is a DBML -> [Fides Dataset](https://ethyca.github.io/fideslang/resources/dataset/) based approach to minimize the amount of work that contributors need to do.

That necessitates verbatim table names, and the default support is just for prettier documentation. See [PyPI](https://dbdocs.io/ewdurbin/PyPI) and [Python.org](https://dbdocs.io/ewdurbin/pythondotorg) for example.

**Comment by imakecodes** [comment]
Hi @ewdurbin, thank you for your patience. I apologize for the delay as I missed the notifications.

I'm happy to inform you that the PRs have been successfully merged and the changes are now live in production, implemented with version 0.7.0

Extra: as this library is going to be used, I'll update it with tests and other important and cool stuffs related to DBML

**Comment by imakecodes** [comment]
Hi @ewdurbin, I hope everything is going well with you.

I would like to know how the project is going and if there is anything else I can help with.
